(cl:in-package mqtt_commx-msg)
(cl:export '(STATE_FLOW-VAL
          STATE_FLOW
          TASK_MODE-VAL
          TASK_MODE
          CHASSIS_TOTAL_HOUR-VAL
          CHASSIS_TOTAL_HOUR
          DRV_DIRECTION-VAL
          DRV_DIRECTION
          FIRM_ERROR_STATE-VAL
          FIRM_ERROR_STATE
          VEHICLE_ERROR_STATUS-VAL
          VEHICLE_ERROR_STATUS
          FAULTS-VAL
          FAULTS
          MILEAGE-VAL
          MILEAGE
          IN_HIGH_VOLTAGE-VAL
          IN_HIGH_VOLTAGE
          VIN-VAL
          VIN
          TASK_ID-VAL
          TASK_ID
          NAVI_ID-VAL
          NAVI_ID
          TASK_TYPE-VAL
          TASK_TYPE
          ACT_TYPE-VAL
          ACT_TYPE
          TARGET-VAL
          TARGET
          SUB_TARGET-VAL
          SUB_TARGET
))