(cl:in-package mqtt_commx-msg)
(cl:export '(MSGTYPE-VAL
          MSGTYPE
          AGVID-VAL
          AGVID
          TIMESTAMP-VAL
          TIMESTAMP
          TASKID-VAL
          TASKID
          TASKTYPE-VAL
          TASKTYPE
          TARGETNAME-VAL
          TARGETNAME
          TARGETX-VAL
          TARGETX
          TARGETY-VAL
          TARGETY
          TARGETHA-VAL
          TARGETHA
          CARGOLENGTH-VAL
          CARGOLENGTH
          CARGOWIDTH-VAL
          CARGOWIDTH
          CARGOWEIGHT-VAL
          CARGOWEIGHT
          CARGOID-VAL
          CARGOID
          WHEELBASE-VAL
          WHEELBASE
          SUBTASKCOUNT-VAL
          SUBTASKCOUNT
          SUBTASKINDEX-VAL
          SUBTASKINDEX
          SUBTASKACTION-VAL
          SUBTASKACTION
          PATHLENGTH-VAL
          PATHLENGTH
          PATH-VAL
          PATH
          VALUE-VAL
          VALUE
          CHANNELID-VAL
          CHANNELID
          CMD-VAL
          CMD
          TIMESEC-VAL
          TIMESEC
          ADDR-VAL
          ADDR
          CMDID-VAL
          CMDID
          CTRLTYPE-VAL
          CTRLTYPE
          STOPPOSX-VAL
          STOPPOSX
          STOPPOSY-VAL
          STOPPOSY
          STOPPOSHA-VAL
          STOPPOSHA
          LIGHTSTATUS-VAL
          LIGHTSTATUS
          LIGHTTYPE-VAL
          LIGHTTYPE
          LIGHTLEFTTIME-VAL
          LIGHTLEFTTIME
          INTERSECTIONID-VAL
          INTERSECTIONID
))