(cl:in-package mqtt_commx-msg)
(cl:export '(HEADER-VAL
          HEADER
          POINT-VAL
          POINT
          FAULTS-VAL
          FAULTS
          ACT_TYPE-VAL
          ACT_TYPE
          CHASSIS_TOTAL_HOUR-VAL
          CHASSIS_TOTAL_HOUR
          DISTANCE_TO_TARGET-VAL
          DISTANCE_TO_TARGET
          DRV_DIRECTION-VAL
          DRV_DIRECTION
          EMPTY-VAL
          EMPTY
          ESTOP-VAL
          ESTOP
          FIRM_ERROR_STATUS-VAL
          FIRM_ERROR_STATUS
          FRAME_TS-VAL
          FRAME_TS
          GEAR-VAL
          GEAR
          IN_HIGH_VOLTAGE-VAL
          IN_HIGH_VOLTAGE
          IS_CHARGING-VAL
          IS_CHARGING
          MILEAGE-VAL
          MILEAGE
          MOTION_MODE-VAL
          MOTION_MODE
          NAVI_ID-VAL
          NAVI_ID
          OPERATIONAL_STATUS-VAL
          OPERATIONAL_STATUS
          PLATFORM_STATE-VAL
          PLATFORM_STATE
          SOC-VAL
          SOC
          SOH-VAL
          SOH
          SPEED-VAL
          SPEED
          STATE_FLOW-VAL
          STATE_FLOW
          SUB_TARGET-VAL
          SUB_TARGET
          TARGET-VAL
          TARGET
          TASK_ID-VAL
          TASK_ID
          TASK_MODE-VAL
          TASK_MODE
          TASK_TYPE-VAL
          TASK_TYPE
          TURN_LIGHT-VAL
          TURN_LIGHT
          VEHICLE_ERROR_STATUS-VAL
          VEHICLE_ERROR_STATUS
          VIN-VAL
          VIN
))