# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mqtt_commx/path_point.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class path_point(genpy.Message):
  _md5sum = "6c29c28350be647e56acc4fdcf5724c5"
  _type = "mqtt_commx/path_point"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 vehSpeed
float64 pointX
float64 pointY
float64 pointHA
"""
  __slots__ = ['vehSpeed','pointX','pointY','pointHA']
  _slot_types = ['float32','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vehSpeed,pointX,pointY,pointHA

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(path_point, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vehSpeed is None:
        self.vehSpeed = 0.
      if self.pointX is None:
        self.pointX = 0.
      if self.pointY is None:
        self.pointY = 0.
      if self.pointHA is None:
        self.pointHA = 0.
    else:
      self.vehSpeed = 0.
      self.pointX = 0.
      self.pointY = 0.
      self.pointHA = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_f3d().pack(_x.vehSpeed, _x.pointX, _x.pointY, _x.pointHA))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.vehSpeed, _x.pointX, _x.pointY, _x.pointHA,) = _get_struct_f3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_f3d().pack(_x.vehSpeed, _x.pointX, _x.pointY, _x.pointHA))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.vehSpeed, _x.pointX, _x.pointY, _x.pointHA,) = _get_struct_f3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f3d = None
def _get_struct_f3d():
    global _struct_f3d
    if _struct_f3d is None:
        _struct_f3d = struct.Struct("<f3d")
    return _struct_f3d
