(cl:in-package mqtt_comm-msg)
(cl:export '(MSGTYPE-VAL
          MSGTYPE
          TIMESTAMP-VAL
          TIMESTAMP
          VERSION-VAL
          VERSION
          MILEAGE-VAL
          MILEAGE
          BATTERYSOH-VAL
          BATTERYSOH
          BATTERYSOC-VAL
          BATTERYSOC
          BATTERYVOLTAGE-VAL
          BATTERYVOLTAGE
          BATTERYCURRENT-VAL
          BATTERYCURRENT
          BATTERYTEMPERATURE-VAL
          BATTERYTEMPERATURE
          CHARGE_STATE-VAL
          CHARGE_STATE
          VEHSPEED-VAL
          VEHSPEED
          POINTHA-VAL
          POINTHA
          POINTX-VAL
          POINTX
          POINTY-VAL
          POINTY
          WORKPOINTID-VAL
          WORKPOINTID
          STEERCONTROLMODE-VAL
          STEERCONTROLMODE
          VEHCTRLMODE-VAL
          VEHCTRLMODE
          AUTODRIVEENABLE-VAL
          AUTODRIVEENABLE
          PITCHANGLE-VAL
          PITCHANGLE
          AZIMUTHANGLE-VAL
          AZIMUTHANGLE
          TASKID-VAL
          TASKID
          TASKSTATUS-VAL
          TASKSTATUS
          ERRCODE-VAL
          ERRCODE
))