(cl:in-package gps-msg)
(cl:export '(HEADER-VAL
          HEADER
          LAT-VAL
          LAT
          LON-VAL
          LON
          UTM_X-VAL
          UTM_X
          UTM_Y-VAL
          UTM_Y
          ANGLE-VAL
          ANGLE
          MAP_X-VAL
          MAP_X
          MAP_Y-VAL
          MAP_Y
          RAW_UTM_X-VAL
          RAW_UTM_X
          RAW_UTM_Y-VAL
          RAW_UTM_Y
          RAW_ANGLE-VAL
          RAW_ANGLE
          RAW_MAP_X-VAL
          RAW_MAP_X
          RAW_MAP_Y-VAL
          RAW_MAP_Y
          MQTT_ANGLE-VAL
          MQTT_ANGLE
          VEL-VAL
          VEL
          QUALITY-VAL
          QUALITY
          HEARTBEAT-VAL
          HEARTBEAT
))