// Generated by gencpp from file mqtt_commx/task.msg
// DO NOT EDIT!


#ifndef MQTT_COMMX_MESSAGE_TASK_H
#define MQTT_COMMX_MESSAGE_TASK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mqtt_commx/path_point.h>

namespace mqtt_commx
{
template <class ContainerAllocator>
struct task_
{
  typedef task_<ContainerAllocator> Type;

  task_()
    : stamp()
    , cmd()
    , subcmd()
    , path()
    , final_path(false)
    , task_id()  {
    }
  task_(const ContainerAllocator& _alloc)
    : stamp()
    , cmd(_alloc)
    , subcmd(_alloc)
    , path(_alloc)
    , final_path(false)
    , task_id(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cmd_type;
  _cmd_type cmd;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _subcmd_type;
  _subcmd_type subcmd;

   typedef std::vector< ::mqtt_commx::path_point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::mqtt_commx::path_point_<ContainerAllocator> >> _path_type;
  _path_type path;

   typedef uint8_t _final_path_type;
  _final_path_type final_path;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_id_type;
  _task_id_type task_id;





  typedef boost::shared_ptr< ::mqtt_commx::task_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mqtt_commx::task_<ContainerAllocator> const> ConstPtr;

}; // struct task_

typedef ::mqtt_commx::task_<std::allocator<void> > task;

typedef boost::shared_ptr< ::mqtt_commx::task > taskPtr;
typedef boost::shared_ptr< ::mqtt_commx::task const> taskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mqtt_commx::task_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mqtt_commx::task_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mqtt_commx::task_<ContainerAllocator1> & lhs, const ::mqtt_commx::task_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.cmd == rhs.cmd &&
    lhs.subcmd == rhs.subcmd &&
    lhs.path == rhs.path &&
    lhs.final_path == rhs.final_path &&
    lhs.task_id == rhs.task_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mqtt_commx::task_<ContainerAllocator1> & lhs, const ::mqtt_commx::task_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mqtt_commx

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mqtt_commx::task_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mqtt_commx::task_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mqtt_commx::task_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mqtt_commx::task_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mqtt_commx::task_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mqtt_commx::task_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mqtt_commx::task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a7c87868fd86cc2f9674d22354ac3c9";
  }

  static const char* value(const ::mqtt_commx::task_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a7c87868fd86cc2ULL;
  static const uint64_t static_value2 = 0xf9674d22354ac3c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::mqtt_commx::task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mqtt_commx/task";
  }

  static const char* value(const ::mqtt_commx::task_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mqtt_commx::task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp         #时间戳\n"
"string cmd         #任务\n"
"string subcmd      #交通信号灯、控制状态\n"
"path_point[] path  #路径\n"
"bool final_path\n"
"string task_id\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: mqtt_commx/path_point\n"
"string id\n"
"float64 pointX\n"
"float64 pointY\n"
"float64 pointHA\n"
"float32 vehSpeed\n"
;
  }

  static const char* value(const ::mqtt_commx::task_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mqtt_commx::task_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.cmd);
      stream.next(m.subcmd);
      stream.next(m.path);
      stream.next(m.final_path);
      stream.next(m.task_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct task_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mqtt_commx::task_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mqtt_commx::task_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cmd);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "subcmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.subcmd);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "path: ";
    if (v.path.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::mqtt_commx::path_point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.path[i]);
    }
    if (v.path.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "final_path: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.final_path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MQTT_COMMX_MESSAGE_TASK_H
