# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mqtt_comm/resp_ctrl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class resp_ctrl(genpy.Message):
  _md5sum = "2f21ac2d8dc240a3fa431fbec8909886"
  _type = "mqtt_comm/resp_ctrl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string msgType
string agvId
int64 timestamp
int32 cmdId
int32 value
string ctrlType



"""
  __slots__ = ['msgType','agvId','timestamp','cmdId','value','ctrlType']
  _slot_types = ['string','string','int64','int32','int32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       msgType,agvId,timestamp,cmdId,value,ctrlType

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(resp_ctrl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.msgType is None:
        self.msgType = ''
      if self.agvId is None:
        self.agvId = ''
      if self.timestamp is None:
        self.timestamp = 0
      if self.cmdId is None:
        self.cmdId = 0
      if self.value is None:
        self.value = 0
      if self.ctrlType is None:
        self.ctrlType = ''
    else:
      self.msgType = ''
      self.agvId = ''
      self.timestamp = 0
      self.cmdId = 0
      self.value = 0
      self.ctrlType = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.msgType
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.agvId
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_q2i().pack(_x.timestamp, _x.cmdId, _x.value))
      _x = self.ctrlType
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msgType = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.msgType = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.agvId = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.agvId = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.timestamp, _x.cmdId, _x.value,) = _get_struct_q2i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ctrlType = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ctrlType = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.msgType
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.agvId
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_q2i().pack(_x.timestamp, _x.cmdId, _x.value))
      _x = self.ctrlType
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msgType = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.msgType = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.agvId = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.agvId = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.timestamp, _x.cmdId, _x.value,) = _get_struct_q2i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ctrlType = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ctrlType = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q2i = None
def _get_struct_q2i():
    global _struct_q2i
    if _struct_q2i is None:
        _struct_q2i = struct.Struct("<q2i")
    return _struct_q2i
