// Generated by gencpp from file mqtt_comm/path_point.msg
// DO NOT EDIT!


#ifndef MQTT_COMM_MESSAGE_PATH_POINT_H
#define MQTT_COMM_MESSAGE_PATH_POINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mqtt_comm/path_point_action.h>

namespace mqtt_comm
{
template <class ContainerAllocator>
struct path_point_
{
  typedef path_point_<ContainerAllocator> Type;

  path_point_()
    : vehSpeed(0.0)
    , pointX(0.0)
    , pointY(0.0)
    , pointHA(0.0)
    , actEnable(false)
    , caption()
    , actions()
    , if_point1()
    , if_point2()  {
    }
  path_point_(const ContainerAllocator& _alloc)
    : vehSpeed(0.0)
    , pointX(0.0)
    , pointY(0.0)
    , pointHA(0.0)
    , actEnable(false)
    , caption(_alloc)
    , actions(_alloc)
    , if_point1(_alloc)
    , if_point2(_alloc)  {
  (void)_alloc;
    }



   typedef float _vehSpeed_type;
  _vehSpeed_type vehSpeed;

   typedef double _pointX_type;
  _pointX_type pointX;

   typedef double _pointY_type;
  _pointY_type pointY;

   typedef double _pointHA_type;
  _pointHA_type pointHA;

   typedef uint8_t _actEnable_type;
  _actEnable_type actEnable;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _caption_type;
  _caption_type caption;

   typedef std::vector< ::mqtt_comm::path_point_action_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::mqtt_comm::path_point_action_<ContainerAllocator> >> _actions_type;
  _actions_type actions;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _if_point1_type;
  _if_point1_type if_point1;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _if_point2_type;
  _if_point2_type if_point2;





  typedef boost::shared_ptr< ::mqtt_comm::path_point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mqtt_comm::path_point_<ContainerAllocator> const> ConstPtr;

}; // struct path_point_

typedef ::mqtt_comm::path_point_<std::allocator<void> > path_point;

typedef boost::shared_ptr< ::mqtt_comm::path_point > path_pointPtr;
typedef boost::shared_ptr< ::mqtt_comm::path_point const> path_pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mqtt_comm::path_point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mqtt_comm::path_point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mqtt_comm::path_point_<ContainerAllocator1> & lhs, const ::mqtt_comm::path_point_<ContainerAllocator2> & rhs)
{
  return lhs.vehSpeed == rhs.vehSpeed &&
    lhs.pointX == rhs.pointX &&
    lhs.pointY == rhs.pointY &&
    lhs.pointHA == rhs.pointHA &&
    lhs.actEnable == rhs.actEnable &&
    lhs.caption == rhs.caption &&
    lhs.actions == rhs.actions &&
    lhs.if_point1 == rhs.if_point1 &&
    lhs.if_point2 == rhs.if_point2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mqtt_comm::path_point_<ContainerAllocator1> & lhs, const ::mqtt_comm::path_point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mqtt_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mqtt_comm::path_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mqtt_comm::path_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mqtt_comm::path_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mqtt_comm::path_point_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mqtt_comm::path_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mqtt_comm::path_point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mqtt_comm::path_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8db6d631c8eb6e7558d6959de9b84eeb";
  }

  static const char* value(const ::mqtt_comm::path_point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8db6d631c8eb6e75ULL;
  static const uint64_t static_value2 = 0x58d6959de9b84eebULL;
};

template<class ContainerAllocator>
struct DataType< ::mqtt_comm::path_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mqtt_comm/path_point";
  }

  static const char* value(const ::mqtt_comm::path_point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mqtt_comm::path_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vehSpeed\n"
"float64 pointX\n"
"float64 pointY\n"
"float64 pointHA\n"
"bool actEnable\n"
"string caption\n"
"path_point_action[] actions\n"
"float32[] if_point1\n"
"float32[] if_point2\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: mqtt_comm/path_point_action\n"
"string caption\n"
"float32[] params\n"
"\n"
"\n"
;
  }

  static const char* value(const ::mqtt_comm::path_point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mqtt_comm::path_point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vehSpeed);
      stream.next(m.pointX);
      stream.next(m.pointY);
      stream.next(m.pointHA);
      stream.next(m.actEnable);
      stream.next(m.caption);
      stream.next(m.actions);
      stream.next(m.if_point1);
      stream.next(m.if_point2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct path_point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mqtt_comm::path_point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mqtt_comm::path_point_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "vehSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.vehSpeed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pointX: ";
    Printer<double>::stream(s, indent + "  ", v.pointX);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pointY: ";
    Printer<double>::stream(s, indent + "  ", v.pointY);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pointHA: ";
    Printer<double>::stream(s, indent + "  ", v.pointHA);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "actEnable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.actEnable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "caption: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.caption);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "actions: ";
    if (v.actions.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.actions.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::mqtt_comm::path_point_action_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.actions[i]);
    }
    if (v.actions.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "if_point1: ";
    if (v.if_point1.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.if_point1.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.if_point1[i]);
    }
    if (v.if_point1.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "if_point2: ";
    if (v.if_point2.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.if_point2.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.if_point2[i]);
    }
    if (v.if_point2.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MQTT_COMM_MESSAGE_PATH_POINT_H
