// Generated by gencpp from file mqtt_comm/resp_video.msg
// DO NOT EDIT!


#ifndef MQTT_COMM_MESSAGE_RESP_VIDEO_H
#define MQTT_COMM_MESSAGE_RESP_VIDEO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mqtt_comm
{
template <class ContainerAllocator>
struct resp_video_
{
  typedef resp_video_<ContainerAllocator> Type;

  resp_video_()
    : agvId()
    , msgType()
    , timestamp(0)
    , result(0)  {
    }
  resp_video_(const ContainerAllocator& _alloc)
    : agvId(_alloc)
    , msgType(_alloc)
    , timestamp(0)
    , result(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _agvId_type;
  _agvId_type agvId;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _msgType_type;
  _msgType_type msgType;

   typedef int64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::mqtt_comm::resp_video_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mqtt_comm::resp_video_<ContainerAllocator> const> ConstPtr;

}; // struct resp_video_

typedef ::mqtt_comm::resp_video_<std::allocator<void> > resp_video;

typedef boost::shared_ptr< ::mqtt_comm::resp_video > resp_videoPtr;
typedef boost::shared_ptr< ::mqtt_comm::resp_video const> resp_videoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mqtt_comm::resp_video_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mqtt_comm::resp_video_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mqtt_comm::resp_video_<ContainerAllocator1> & lhs, const ::mqtt_comm::resp_video_<ContainerAllocator2> & rhs)
{
  return lhs.agvId == rhs.agvId &&
    lhs.msgType == rhs.msgType &&
    lhs.timestamp == rhs.timestamp &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mqtt_comm::resp_video_<ContainerAllocator1> & lhs, const ::mqtt_comm::resp_video_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mqtt_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mqtt_comm::resp_video_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mqtt_comm::resp_video_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mqtt_comm::resp_video_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mqtt_comm::resp_video_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mqtt_comm::resp_video_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mqtt_comm::resp_video_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mqtt_comm::resp_video_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8df69503833d0a76a10ba40c1b67964";
  }

  static const char* value(const ::mqtt_comm::resp_video_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8df69503833d0a7ULL;
  static const uint64_t static_value2 = 0x6a10ba40c1b67964ULL;
};

template<class ContainerAllocator>
struct DataType< ::mqtt_comm::resp_video_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mqtt_comm/resp_video";
  }

  static const char* value(const ::mqtt_comm::resp_video_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mqtt_comm::resp_video_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string agvId \n"
"string msgType\n"
"int64 timestamp\n"
"int32 result \n"
"\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::mqtt_comm::resp_video_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mqtt_comm::resp_video_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.agvId);
      stream.next(m.msgType);
      stream.next(m.timestamp);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct resp_video_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mqtt_comm::resp_video_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mqtt_comm::resp_video_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "agvId: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.agvId);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "msgType: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.msgType);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<int64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MQTT_COMM_MESSAGE_RESP_VIDEO_H
