# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pathtrack/track_state.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class track_state(genpy.Message):
  _md5sum = "976fb87d357afb82707050b80adee235"
  _type = "pathtrack/track_state"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 timestamp
string stopReason
int32 self_turn_ctr
int32 turnmode_ctr
float32 track_angle_err
float32 track_dis_err
float32 aim_range
float32 steering_property
"""
  __slots__ = ['timestamp','stopReason','self_turn_ctr','turnmode_ctr','track_angle_err','track_dis_err','aim_range','steering_property']
  _slot_types = ['int64','string','int32','int32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,stopReason,self_turn_ctr,turnmode_ctr,track_angle_err,track_dis_err,aim_range,steering_property

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(track_state, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.stopReason is None:
        self.stopReason = ''
      if self.self_turn_ctr is None:
        self.self_turn_ctr = 0
      if self.turnmode_ctr is None:
        self.turnmode_ctr = 0
      if self.track_angle_err is None:
        self.track_angle_err = 0.
      if self.track_dis_err is None:
        self.track_dis_err = 0.
      if self.aim_range is None:
        self.aim_range = 0.
      if self.steering_property is None:
        self.steering_property = 0.
    else:
      self.timestamp = 0
      self.stopReason = ''
      self.self_turn_ctr = 0
      self.turnmode_ctr = 0
      self.track_angle_err = 0.
      self.track_dis_err = 0.
      self.aim_range = 0.
      self.steering_property = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.timestamp
      buff.write(_get_struct_q().pack(_x))
      _x = self.stopReason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i4f().pack(_x.self_turn_ctr, _x.turnmode_ctr, _x.track_angle_err, _x.track_dis_err, _x.aim_range, _x.steering_property))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      (self.timestamp,) = _get_struct_q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.stopReason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.stopReason = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.self_turn_ctr, _x.turnmode_ctr, _x.track_angle_err, _x.track_dis_err, _x.aim_range, _x.steering_property,) = _get_struct_2i4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.timestamp
      buff.write(_get_struct_q().pack(_x))
      _x = self.stopReason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i4f().pack(_x.self_turn_ctr, _x.turnmode_ctr, _x.track_angle_err, _x.track_dis_err, _x.aim_range, _x.steering_property))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      (self.timestamp,) = _get_struct_q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.stopReason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.stopReason = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.self_turn_ctr, _x.turnmode_ctr, _x.track_angle_err, _x.track_dis_err, _x.aim_range, _x.steering_property,) = _get_struct_2i4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i4f = None
def _get_struct_2i4f():
    global _struct_2i4f
    if _struct_2i4f is None:
        _struct_2i4f = struct.Struct("<2i4f")
    return _struct_2i4f
_struct_q = None
def _get_struct_q():
    global _struct_q
    if _struct_q is None:
        _struct_q = struct.Struct("<q")
    return _struct_q
